#!/bin/bash

FOREVER=/usr/local/bin/forever
LOG_OPTIONS="--append -o /home/pi/logs/heating.log -e /home/pi/logs/heating.err"
SERVER_JS_FILE=/home/pi/nodejs/heating/app/app.js
USER=pi

case "$1" in

start)
  echo "starting forever: $FOREVER start $LOG_OPTIONS $SERVER_JS_FILE"
  sudo -u $USER $FOREVER start $LOG_OPTIONS $SERVER_JS_FILE
  ;;

stop)
  $FOREVER stopall
  ;;

*)
  echo "usage: $0 (start|stop)"
esac

exit 0
